name: "🐛 Bug Report"
description: Report a suspected bug in the DeepSensor package.
title: "Potential bug: <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter a specific description of your issue
      placeholder: Short and specific description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter the steps that you took so we can try to reproduce the issue.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: "Version"
      description: Please tell us which version of DeepSensor you're using.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: Which OS are you using?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: false